### ISSUE TITLE
k8s部署中，数据库用外部，要怎么修改

### ISSUE THREAD

**Issue by weihc02** [idoop/docker-apollo#10]
k8s部署中，数据库用外部，要怎么修改

**Comment by idoop** [comment]
只需将`env`中的数据库地址改成目标地址即可.
``` yaml
  containers:
  - env:
      # 替换为 DEV_DB / FAT_DB / UAT_DB / PRO_DB / PORTAL_DB
    - name: XX_DB
      # 或者用域名  jdbc:mysql://mysql.addr.com:3306/xxx ,确保内部能够解析出IP且能访问即可.
      value: jdbc:mysql://1.2.3.4:3306/DbName?characterEncoding=utf8
    - name: XX_DB_USER
      value: username
    - name: XX_DB_PWD
      value: password
```

**Comment by weihc02** [comment]
请问一下，k8s部署apollo多环境，在您的示例配置文件如何追加yaml文件呢，能给模板吗？

**Comment by weihc02** [comment]
同时admin 如何配置呢，示例中没有admin

**Comment by idoop** [comment]
`admin`不需要特殊的配置,这个服务是给`portal`用的,在k8s环境中的绝大部分场景是客户端访问`config`获取配置,因此可以设置`ONLY_CONFIG`参数不启动`admin`以节约资源.

k8s中部署多个Apollo环境, 是指用多个`Deployment`类型部署不同的Apollo环境,还是在一个`Deployment`的`Pod`中启动多个Apollo环境呢?

用多个`Deployment`的话,只需修改为对应Apollo环境的`env`参数,再和`Service`绑定默认端口即可.

如果是在一个`Pod`中启动多个Apollo环境,只用添加你想要的环境的`env`参数,再开放相应的端口即可,例如你想开启dev和fat的Apollo环境:
``` yaml
kind: Deployment
# ...
  containers:
  - name: multie-apollo-env
    env: 
     - name: DEV_DB
        value: jdbc:mysql://1.2.3.4:3306/DevDbName?characterEncoding=utf8
     # ... set db account & pwd
     - name: FAT_DB
        value: jdbc:mysql://1.2.3.4:3306/FatDbName?characterEncoding=utf8
      # ...
    ports:
    - name: dev-cfg-port
      containerPort: 8080
    # 如果启动admin了,则暴露端口
    - name: dev-adm-port
      containerPort: 8090
    - name: fat-cfg-port
      containerPort: 8081
    - name: fat-adm-port
      containerPort: 8091
  # 在一个pod中启动多个Apollo环境则readiness和liveness的检测方式使用exec
    readinessProbe:
      initialDelaySeconds: 100
      periodSeconds: 20
      exec:
        command:
        - healthcheck
    # liveness的配置类似readiness,但initialDelaySeconds要设置稍大些.

---
kind: Service
# ...
spec:
  ports:
  - name: dev-cfg-port
    port: 你要暴露dev config的端口
    targetPort: 8080
  - name: def-adm-port
    port: 你要暴露dev admin的端口
  - name: fat-cfg-port
    port: 你要暴露fat config的端口
    targetPort: 8081
  - name: fat-adm-port
    port: 你要暴露fat admin的端口
    targetPort: 8091
  # ...
```
可以参考`wiki`中`docker-compose`的yaml部署模板,里面其实和在k8s中的部署是极其类似的,思想都是一样的.
