### ISSUE TITLE
k8s部署了一个开发环境，protal报错，登录页面没有可以添加项目

### ISSUE THREAD

**Issue by weihc02** [idoop/docker-apollo#11]
k8s部署了一个开发环境，protal报错，登录页面没有可以添加项目
2018-12-19 09:58:08.089 ERROR 532 --- [Apollo-EnvHealthChecker-1] c.c.f.a.portal.component.PortalSettings  : Env is down. env: DEV, failed times: 191, meta server address: http://localhost:8080/

**Comment by weihc02** [comment]
截图 
![image](https://user-images.githubusercontent.com/17331776/50194994-3d3ede80-0378-11e9-8162-0ee0dfcdf366.png)

**Comment by idoop** [comment]
Portal依赖`admin`提供服务,但会先访问`config`的Eureka,所以确保至少有一个`admin`服务注册到了Eureka中.

建议先看看官方的wiki,再按照官方的指导部署一遍,大致理解了Apollo的运行原理,就知道怎么回事了,再用这个镜像就知道那些env参数干什么用的.

**Comment by weihc02** [comment]
还有一个疑问，想问下，已经部署了dev环境，现在想增加一个fat环境，portal共用，只需要部署fat_config吗？ 如下：
``` yaml
#fat_config配置
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: apollo-fat
  name: apollo-fat
  namespace: config
spec:
  # 根据client数量配置实例数
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: apollo-fat
  template:
    metadata:
      labels:
        app: apollo-fat
    spec:
        # 部署标签work节点apollo的
      nodeSelector:
        node: "apollo"

      containers:
      - name: apollo-fat
        image: 192.168.3.10:5001/third_party/idoop-apollo:v1.2.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: config-port
          containerPort: 8081
        readinessProbe:
          httpGet:
            path: /
            port: config-port
          # 启动较慢,可以适量改大,如果同时要开启admin,或者同时开启其他环境服务,比如uat或pro,则设置的预备时间值翻倍
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 3
        livenessProbe:
          # 同预备时间相似,但如果要同时启动admin或启动多个环境的服务,则等待时长必须要大于全部服务启动完的时长
          # 因为一旦没能启动完成,则健康检查失败将会陷入无限重启的状态
          # 如果只有一个环境并设置了ONLY_CONFIG,则健康检查可以替换为httpGet方式.
          initialDelaySeconds: 50
          periodSeconds: 10
          exec:
            command:
            - healthcheck
        env:
        # 如果想在容器中同时运行admin,则不要配置ONLY_CONFIG
        - name: ONLY_CONFIG
          value: "TRUE"
        # 如果mysql也在k8s集群中,则地址可以直接配置MySQL服务名.
        - name: FAT_DB
          value: jdbc:mysql://xxxxxx:3306/fatapolloconfigdb?characterEncoding=utf8
        - name: FAT_DB_USER
          value: test_apollo
        - name: FAT_DB_PWD
          value: Apollo_2018
         # 如果设置了ONLY_CONFIG,则可以不配置LB
#        - name: DEV_LB
#          value: apollo-fat
      terminationGracePeriodSeconds: 5
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: apollo-fat
  name: apollo-fat
  namespace: config
spec:
  ports:
  - name: config-port
    port: 8081
    targetPort: 8081
  selector:
    app: apollo-fat
```
------
Portal  env 还用增加一个fat连接吗？
``` yaml
    - name: FAT_DB
      value: jdbc:mysql://rm-wz954l5bqan12zwta147.mysql.rds.aliyuncs.com:3306/fatapolloconfigdb?characterEncoding=utf8
    - name: FAT_DB_USER
      value: test_apollo
    - name: FAT_DB_PWD
      value: Apollo_2018    
```

**Comment by idoop** [comment]
只需在Portal的yaml文件中添加`FAT_URL`键值即可,并且确保有`admin`服务向这个地址的`config`服务中的Eureka注册.

**Comment by weihc02** [comment]
像这样
![image](https://user-images.githubusercontent.com/17331776/50206691-282d7400-03a7-11e9-9bd6-a5684e245ff3.png)
不用在Portal的yaml文件中,类似如下
  - name: FAT_DB
      value: jdbc:mysql://xxxxx:3306/fatapolloconfigdb?characterEncoding=utf8
    - name: FAT_DB_USER
      value: test_apollo
    - name: FAT_DB_PWD
      value: Apollo_2018

**Comment by idoop** [comment]
`FAT_URL`这个参数是给portal用的.请看一下主页的[env参数](https://github.com/idoop/docker-apollo#environment-%E5%8F%82%E6%95%B0)的说明,里面介绍的很详细了.

**Comment by weihc02** [comment]
加了这个url之后，admin 8091没有起来，参数像是不生效，
![image](https://user-images.githubusercontent.com/17331776/50207273-f1585d80-03a8-11e9-9ef7-8f1a32def81d.png)
fat confi服务需要调整什么吗？
现fat 配置如下
``` yaml
#fat_config配置
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: apollo-fat
  name: apollo-fat
  namespace: config
spec:
  # 根据client数量配置实例数
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: apollo-fat
  template:
    metadata:
      labels:
        app: apollo-fat
    spec:
        # 部署标签work节点apollo的
      nodeSelector:
        node: "apollo"

      containers:
      - name: apollo-fat
        image: 192.168.3.10:5001/third_party/idoop-apollo:v1.2.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: config-port
          containerPort: 8081
        readinessProbe:
          httpGet:
            path: /
            port: config-port
          # 启动较慢,可以适量改大,如果同时要开启admin,或者同时开启其他环境服务,比如uat或pro,则设置的预备时间值翻倍
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 3
        livenessProbe:
          # 同预备时间相似,但如果要同时启动admin或启动多个环境的服务,则等待时长必须要大于全部服务启动完的时长
          # 因为一旦没能启动完成,则健康检查失败将会陷入无限重启的状态
          # 如果只有一个环境并设置了ONLY_CONFIG,则健康检查可以替换为httpGet方式.
          initialDelaySeconds: 50
          periodSeconds: 10
          exec:
            command:
            - healthcheck
        env:
        # 如果想在容器中同时运行admin,则不要配置ONLY_CONFIG
        - name: ONLY_CONFIG
          value: "TRUE"
        # 如果mysql也在k8s集群中,则地址可以直接配置MySQL服务名.
        - name: FAT_DB
          value: jdbc:mysql://xxxxxx:3306/fatapolloconfigdb?characterEncoding=utf8
        - name: FAT_DB_USER
          value: test_apollo
        - name: FAT_DB_PWD
          value: Apollo_2018
         # 如果设置了ONLY_CONFIG,则可以不配置LB
#        - name: DEV_LB
#          value: apollo-fat
      terminationGracePeriodSeconds: 5
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: apollo-fat
  name: apollo-fat
  namespace: config
spec:
  ports:
  - name: config-port
    port: 8081
    targetPort: 8081
  selector:
    app: apollo-fat
```
