### ISSUE TITLE
docker-compose.yaml 部署/启动失败

### ISSUE THREAD

**Issue by eddycjy** [idoop/docker-apollo#13]
## docker-compose.yaml

```
version: '2'
services:
  apollo:
    image: idoop/docker-apollo:latest
    # portal若出现504错误,则将网络模式改为host. host模式下如果想改端口,参考下方修改端口的环境变量
    # network_mode: "host"
    # volumes:
      # 如果需要查看日志,挂载容器中的/opt路径出来即可.
    #  - ./logs:/opt
      # 如果portal需要开启ldap或ad域验证,须挂载此ldap配置文件
    #  - ./application-ldap.yml:/apollo-portal/config/application-ldap.yml:ro
    environment:
      # 开启Portal,默认端口: 8070
      PORTAL_DB: jdbc:mysql://localhost:3307/ApolloPortalDB?characterEncoding=utf8
      PORTAL_DB_USER: root
      PORTAL_DB_PWD: rootroot
      # 如果portal需要开启ldap或ad域验证,须设置该环境变量为TRUE
      #PORTAL_LDAP: "TRUE"

      # 开启dev环境, 默认端口: config 8080, admin 8090
      DEV_DB: jdbc:mysql://localhost:3307/ApolloConfigDBDev?characterEncoding=utf8
      DEV_DB_USER: root
      DEV_DB_PWD: rootroot

      # 开启fat环境, 默认端口: config 8081, admin 8091
      FAT_DB: jdbc:mysql://localhost:3307/ApolloConfigDBFat?characterEncoding=utf8
      FAT_DB_USER: root
      FAT_DB_PWD: rootroot
      # 可修改端口.
      FAT_CONFIG_PORT: 8050
      FAT_ADMIN_PORT: 8051

      # 指定远程uat地址
      #UAT_URL: http://192.168.1.2:8080

      # 指定远程pro地址
      #PRO_URL: http://www.example.com:8080
```

## 响应结果

```
$ docker-compose up   
docker_apollo_apollo_1 is up-to-date
Attaching to docker_apollo_apollo_1
apollo_1  | + '[' 0 == 0 ']'
apollo_1  | + [[ -n jdbc:mysql://localhost:3307/ApolloPortalDB?characterEncoding=utf8 ]]
apollo_1  | + startPortal
apollo_1  | + [[ ! -d /apollo-portal/scripts ]]
apollo_1  | + unzip /apollo-portal-1.2.0-github.zip -d /apollo-portal
apollo_1  | Archive:  /apollo-portal-1.2.0-github.zip
apollo_1  |    creating: scripts/
apollo_1  |   inflating: scripts/startup.sh
apollo_1  |   inflating: scripts/shutdown.sh
apollo_1  |    creating: config/
apollo_1  |   inflating: config/app.properties
apollo_1  |   inflating: apollo-portal.conf
apollo_1  |   inflating: config/application-github.properties
apollo_1  |   inflating: config/apollo-env.properties
apollo_1  |   inflating: apollo-portal-1.2.0.jar
apollo_1  |   inflating: apollo-portal-1.2.0-sources.jar
apollo_1  | + sed -i -e '/^SERVER_PORT=.*$/a\export JAVA_OPTS="$JAVA_OPTS -Dspring.datasource.url=jdbc:mysql://localhost:3307/ApolloPortalDB?characterEncoding=utf8 "' /apollo-portal/scripts/startup.sh
apollo_1  | + [[ -n root ]]
apollo_1  | + sed -i -e '/^SERVER_PORT=.*$/a\export JAVA_OPTS="$JAVA_OPTS -Dspring.datasource.username=root "' /apollo-portal/scripts/startup.sh
apollo_1  | + [[ -n rootroot ]]
apollo_1  | + sed -i -e '/^SERVER_PORT=.*$/a\export JAVA_OPTS="$JAVA_OPTS -Dspring.datasource.password=rootroot "' /apollo-portal/scripts/startup.sh
apollo_1  | + [[ -n 8070 ]]
apollo_1  | + sed -i -e 's/^SERVER_PORT=.*$/SERVER_PORT=8070/' /apollo-portal/scripts/startup.sh
apollo_1  | + [[ -n '' ]]
apollo_1  | + [[ -n '' ]]
apollo_1  | + [[ -n '' ]]
apollo_1  | + [[ -n '' ]]
apollo_1  | + [[ -n '' ]]
apollo_1  | + [[ -n jdbc:mysql://localhost:3307/ApolloConfigDBDev?characterEncoding=utf8 ]]
apollo_1  | + startENV dev 'jdbc:mysql://localhost:3307/ApolloConfigDBDev?characterEncoding=utf8' root rootroot 8090 8080
apollo_1  | + targetENV=dev
apollo_1  | + targetDb='jdbc:mysql://localhost:3307/ApolloConfigDBDev?characterEncoding=utf8'
apollo_1  | + targetDbUser=root
apollo_1  | + targetDbPwd=rootroot
apollo_1  | + targetAdminPort=8090
apollo_1  | + targetConfigPort=8080
apollo_1  | + targetEnvAddr=
apollo_1  | + [[ ! -d /apollo-config/dev/scripts ]]
apollo_1  | + unzip /apollo-configservice-1.2.0-github.zip -d /apollo-config/dev
apollo_1  | Archive:  /apollo-configservice-1.2.0-github.zip
apollo_1  |    creating: scripts/
apollo_1  |   inflating: scripts/startup.sh
apollo_1  |   inflating: scripts/shutdown.sh
apollo_1  |    creating: config/
apollo_1  |   inflating: config/app.properties
apollo_1  |   inflating: apollo-configservice.conf
apollo_1  |   inflating: config/application-github.properties
apollo_1  |   inflating: apollo-configservice-1.2.0-sources.jar
apollo_1  |   inflating: apollo-configservice-1.2.0.jar
apollo_1  | + sed -i -e '/^SERVER_PORT=.*$/a\export JAVA_OPTS="$JAVA_OPTS -Dspring.datasource.url=jdbc:mysql://localhost:3307/ApolloConfigDBDev?characterEncoding=utf8 "' /apollo-config/dev/scripts/startup.sh
apollo_1  | + sed -i -e '/^SERVER_PORT=.*$/a\export JAVA_OPTS="$JAVA_OPTS -Dspring.datasource.username=root "' /apollo-config/dev/scripts/startup.sh
apollo_1  | + sed -i -e '/^SERVER_PORT=.*$/a\export JAVA_OPTS="$JAVA_OPTS -Dspring.datasource.password=rootroot "' /apollo-config/dev/scripts/startup.sh
apollo_1  | + [[ -n 8080 ]]
apollo_1  | + sed -i -e 's/^SERVER_PORT=.*$/SERVER_PORT=8080/' /apollo-config/dev/scripts/startup.sh
apollo_1  | + [[ -n jdbc:mysql://localhost:3307/ApolloPortalDB?characterEncoding=utf8 ]]
apollo_1  | + sed -i -r '/-Ddev_meta=.*$/d' /apollo-portal/scripts/startup.sh
apollo_1  | + sed -i -e '/^SERVER_PORT=.*$/a\export JAVA_OPTS="$JAVA_OPTS -Ddev_meta=http://localhost:8080/"' /apollo-portal/scripts/startup.sh
apollo_1  | + [[ -n '' ]]
apollo_1  | + /apollo-config/dev/scripts/startup.sh
apollo_1  | Mon Mar 18 02:34:29 UTC 2019 ==== Starting ==== 
apollo_1  | Started [50]
apollo_1  | Waiting for server startup......
apollo_1  | pid - 50 just quit unexpectedly, please check logs under /opt/logs/100003171 and /tmp for more information!
apollo_1  | + '[' 0 == 0 ']'
apollo_1  | + [[ -n jdbc:mysql://localhost:3307/ApolloPortalDB?characterEncoding=utf8 ]]
apollo_1  | + startPortal
apollo_1  | + [[ ! -d /apollo-portal/scripts ]]
apollo_1  | + [[ -n '' ]]
apollo_1  | + [[ -n jdbc:mysql://localhost:3307/ApolloConfigDBDev?characterEncoding=utf8 ]]
apollo_1  | + startENV dev 'jdbc:mysql://localhost:3307/ApolloConfigDBDev?characterEncoding=utf8' root rootroot 8090 8080
apollo_1  | + targetENV=dev
apollo_1  | + targetDb='jdbc:mysql://localhost:3307/ApolloConfigDBDev?characterEncoding=utf8'
apollo_1  | + targetDbUser=root
apollo_1  | + targetDbPwd=rootroot
apollo_1  | + targetAdminPort=8090
apollo_1  | + targetConfigPort=8080
apollo_1  | + targetEnvAddr=
apollo_1  | + [[ ! -d /apollo-config/dev/scripts ]]
apollo_1  | + /apollo-config/dev/scripts/startup.sh
apollo_1  | Mon Mar 18 02:41:03 UTC 2019 ==== Starting ==== 
apollo_1  | Started [40]
apollo_1  | Waiting for server startup.....
apollo_1  | pid - 40 just quit unexpectedly, please check logs under /opt/logs/100003171 and /tmp for more information!
apollo_1  | + '[' 0 == 0 ']'
apollo_1  | + [[ -n jdbc:mysql://localhost:3307/ApolloPortalDB?characterEncoding=utf8 ]]
apollo_1  | + startPortal
apollo_1  | + [[ ! -d /apollo-portal/scripts ]]
apollo_1  | + [[ -n '' ]]
apollo_1  | + [[ -n jdbc:mysql://localhost:3307/ApolloConfigDBDev?characterEncoding=utf8 ]]
apollo_1  | + startENV dev 'jdbc:mysql://localhost:3307/ApolloConfigDBDev?characterEncoding=utf8' root rootroot 8090 8080
apollo_1  | + targetENV=dev
apollo_1  | + targetDb='jdbc:mysql://localhost:3307/ApolloConfigDBDev?characterEncoding=utf8'
apollo_1  | + targetDbUser=root
apollo_1  | + targetDbPwd=rootroot
apollo_1  | + targetAdminPort=8090
apollo_1  | + targetConfigPort=8080
apollo_1  | + targetEnvAddr=
apollo_1  | + [[ ! -d /apollo-config/dev/scripts ]]
apollo_1  | + /apollo-config/dev/scripts/startup.sh
apollo_1  | Mon Mar 18 02:43:22 UTC 2019 ==== Starting ==== 
apollo_1  | Started [39]
apollo_1  | Waiting for server startup.....
apollo_1  | pid - 39 just quit unexpectedly, please check logs under /opt/logs/100003171 and /tmp for more information!
```

## 问题

1. Apollo 无法启动
2. /opt/logs/100003171 和 /tmp 下均没有发现 Apollo 相关的日志

## 期望结果

正常启动 Apollo 并访问
