### ISSUE TITLE
k8s部署dev，启用了admin，但portal访问不到apollo-dev

### ISSUE THREAD

**Issue by wolking** [idoop/docker-apollo#14]
![Uploading image.png…]()
# 但如果config服务中启动了admin,则config数据库的ServerConfig表中eureka.service.url的地址应该是config的svc名称与对外的端口
        # 以本次为例,svc为apollo-dev,端口为8080,portal则只需指定DEV_URL,类似下方.
        - name: DEV_URL
          value: http://apollo-dev:8080

portal启动保错：

`org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://apollo-dev:8090/health": Connect to apollo-dev:8090 [apollo-dev/10.68.23.250] failed: connect timed out; nested exception is org.apache.http.conn.ConnectTimeoutException: Connect to apollo-dev:8090 [apollo-dev/10.68.23.250] failed: connect timed out
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:696)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:644)
	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:296)
	at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.doExecute(RetryableRestTemplate.java:190)
	at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.execute(RetryableRestTemplate.java:95)
	at com.ctrip.framework.apollo.portal.component.RetryableRestTemplate.get(RetryableRestTemplate.java:56)
	at com.ctrip.framework.apollo.portal.api.AdminServiceAPI$HealthAPI.health(AdminServiceAPI.java:43)
	at com.ctrip.framework.apollo.portal.component.PortalSettings$HealthCheckTask.isUp(PortalSettings.java:127)
	at com.ctrip.framework.apollo.portal.component.PortalSettings$HealthCheckTask.run(PortalSettings.java:103)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to apollo-dev:8090 [apollo-dev/10.68.23.250] failed: connect timed out
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:151)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:394)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.springframework.http.client.HttpComponentsClientHttpRequest.executeInternal(HttpComponentsClientHttpRequest.java:87)
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:687)
	... 15 common frames omitted
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	... 28 common frames omitted
`
看起来配置不起作用，默认访问8090端口，而不是8080端口

**Comment by idoop** [comment]
@wolking 能否贴一下你的yaml配置?

**Comment by wolking** [comment]
我自己搞出来了，多开放了admin所占的端口就没出错了。
**config与admin的：**

```
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: apollo-dev
  name: apollo-dev
  namespace: default
spec:
  # 根据client数量配置实例数
  replicas: 1
  #revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: apollo-dev
  template:
    metadata:
      labels:
        app: apollo-dev
    spec:
      containers:
        - name: apollo-dev
          image: idoop/docker-apollo:latest
          volumeMounts:
            - mountPath: /opt
              name: apollo-dev-log
          imagePullPolicy: IfNotPresent
          ports:
            - name: config-port
              containerPort: 28080
            - name: admin-port
              containerPort: 28090
          readinessProbe:
            httpGet:
              path: /
              port: config-port
            # 启动较慢,可以适量改大,如果同时要开启admin,或者同时开启其他环境服务,比如uat或pro,则设置的预备时间值翻倍
            initialDelaySeconds: 80
            periodSeconds: 20
            timeoutSeconds: 3
          livenessProbe:
            # 同预备时间相似,但如果要同时启动admin或启动多个环境的服务,则等待时长必须要大于全部服务启动完的时长
            # 因为一旦没能启动完成,则健康检查失败将会陷入无限重启的状态
            # 如果只有一个环境并设置了ONLY_CONFIG,则健康检查可以替换为httpGet方式.
            initialDelaySeconds: 100
            periodSeconds: 10
            exec:
              command:
                - healthcheck
          env:
            # 如果想在容器中同时运行admin,则不要配置ONLY_CONFIG
            # - name: ONLY_CONFIG
            #  value: "TRUE"
            # 如果mysql也在k8s集群中,则地址可以直接配置MySQL服务名.
            - name: DEV_DB
              value: jdbc:mysql://mysql:3306/ApolloConfigDBDev?characterEncoding=utf8
            - name: DEV_DB_USER
              value: root
            - name: DEV_DB_PWD
              value: xxx
            #修改config服务默认端口8080为28080
            - name: DEV_CONFIG_PORT
              value: "28080"
            #修改admin服务默认端口8090为28090
            - name: DEV_ADMIN_PORT
              value: "28090"
              # 如果设置了ONLY_CONFIG,则可以不配置LB。
              #对-Deureka.instance.ip-address进行配置，当config与admin处于docker容器的环境下，为能被portal或者admin访问，需配置该项
            - name: DEV_LB
              value: 192.168.36.175
      terminationGracePeriodSeconds: 5
      volumes:
        - name: apollo-dev-log
          hostPath:
            path: /opt/apollo/dev

```

**config与admin的service配置：**
```
kind: Service
apiVersion: v1
metadata:
  labels:
    app: apollo-dev
  name: apollo-dev
  namespace: default
spec:
  type: NodePort
  ports:
    - name: config-port
      port: 28080
      targetPort: 28080
      nodePort: 28080
    - name: admin-port
      port: 28090
      targetPort: 28090
      nodePort: 28090
  selector:
    app: apollo-dev
```

**portal deployment：**

```
kind: Pod
apiVersion: v1
metadata:
  labels:
    app: apollo-portal
  name: apollo-portal
  namespace: default
spec:
  containers:
    - name: apollo-portal
      image: idoop/docker-apollo:latest
      volumeMounts:
        - mountPath: /opt
          name: apollo-portal-log
      imagePullPolicy: IfNotPresent
      ports:
        - name: portal-port
          containerPort: 8070
      # 如无必要,可以不暴露portal中的admin和config
      #- name: config-port
      #  containerPort: 8080
      #- name: admin-port
      #  containerPort: 8090
      readinessProbe:
        initialDelaySeconds: 200
        periodSeconds: 20
        exec:
          command:
            - healthcheck
      livenessProbe:
        initialDelaySeconds: 300
        periodSeconds: 10
        exec:
          command:
            - healthcheck
      env:
        - name: PORTAL_DB
          value: jdbc:mysql://mysql:3306/ApolloPortalDB?characterEncoding=utf8
        - name: PORTAL_DB_USER
          value: root
        - name: PORTAL_DB_PWD
          value: xxx

        # 如果config服务部署中没配置启动admin,则config的数据库的ServerConfig表中eureka.service.url的地址建议配置为localhost
        # - name: DEV_DB
        #   value: jdbc:mysql://mysql:3306/ApolloConfigDBDev?characterEncoding=utf8
        # - name: DEV_DB_USER
        #   value: root
        # - name: DEV_DB_PWD
        #   value: xxx
        # 但如果config服务中启动了admin,则config数据库的ServerConfig表中eureka.service.url的地址应该是config的svc名称与对外的端口
        # 以本次为例,svc为apollo-dev,端口为8080,portal则只需指定DEV_URL,类似下方.
        - name: DEV_URL
          value: http://192.168.36.175:28080
  volumes:
    - name: apollo-portal-log
      hostPath:
        path: /opt/apollo/portal
```

**portal service：**

```
kind: Service
apiVersion: v1
metadata:
  labels:
    app: apollo-portal
  name: apollo-portal
  namespace: default
spec:
  type: NodePort
  ports:
  - name: portal-port
    port: 8070
    targetPort: 8070
    nodePort: 28070
  # 如无必要,可以不暴露portal中的admin和config
  #- name: admin-port
  #- name: config-port
  selector:
    app: apollo-portal
```
