### ISSUE TITLE
想请教如何启动

### ISSUE THREAD

**Issue by soupedog** [idoop/docker-apollo#4]
我的目的是想启动 portal + fat 环境

docker-compose.yaml 配置文件为

```
version: '2'
services:
  apollo:
    image: idoop/docker-apollo:latest
    container_name: apollo
    network_mode: "host"
    restart: always
# 启动前,确认对应环境的数据库已经建立，否则apollo无法启动.
# 默认端口:portal:8070; dev:8080,8090; fat:8081,8091; uat:8082,8092; pro:8083,8093
    environment:
      PORTAL_DB: jdbc:mysql://192.168.12.70:3306/ApolloPortalDB?characterEncoding=utf8
      PORTAL_DB_USER: root
      PORTAL_DB_PWD: 1111
#      PORTAL_PORT: 80

      DEV_DB: 
      DEV_DB_USER: root
      DEV_DB_PWD: password
      
      FAT_DB: jdbc:mysql://192.168.12.70:3306/ApolloConfigDBFat?characterEncoding=utf8
      FAT_DB_USER: root
      FAT_DB_PWD: 1111

      UAT_DB: 
      UAT_DB_USER: root
      UAT_DB_PWD: password

      PRO_DB: 
      PRO_DB_USER: root
      PRO_DB_PWD: password

```

成功执行了 build.sh
``` shell
#!/bin/bash
name="apollo-test"
tag=$(date +"%m%d%H%M%S")

docker build -t ${name}:${tag} .

oldImage=$(docker images | grep ${name} | grep -v ${tag} | awk -vOFS=":" '{ print $1,$2 }')
if [[ -n ${oldImage} ]];then
    echo "Delete old Image: ${oldImage}"
    docker rmi ${oldImage}
fi
```

在本地成功生成了 apollo-test 的 docker 镜像

然后我执行了 ``docker run --name apollo-test  -d -p 8070:8070 -p 8081:8081 -p 8091:8091  apollo-test`` 然后我访问 localhost:8070 没有任何反应，docker 容器也是 up 状态，`` docker exec -it apollo-test 
 /bin/sh`` 进入容器内部 我也没找到 ``/opt/log`` 文件夹

想问问我的用法是否有错呢？

**Comment by idoop** [comment]
``` yaml
version: '2'
services:
  apollo:
    image: idoop/docker-apollo:latest
    container_name: apollo
    network_mode: "host"
    restart: always
    environment:
      PORTAL_DB: jdbc:mysql://192.168.12.70:3306/ApolloPortalDB?characterEncoding=utf8
      PORTAL_DB_USER: root
      PORTAL_DB_PWD: 1111
      FAT_DB: jdbc:mysql://192.168.12.70:3306/ApolloConfigDBFat?characterEncoding=utf8
      FAT_DB_USER: root
      FAT_DB_PWD: 1111
# 上面配置是没有问题，你需要检查下数据库的配置是否正确
# 直接挂载出日志即可
    volumes:
      - ./logs:/opt
```
