### ISSUE TITLE
使用docker-compose方式部署，加入DEV_URL后启动不成功，直接跳出启动

### ISSUE THREAD

**Issue by jackenwjk** [idoop/docker-apollo#9]
compose如下：
version: '2'
services:
  apollo:
    image: idoop/docker-apollo:latest
    # portal若出现504错误,则将网络模式改为host. host模式下如果想改端口,参考下方修改端口的环境变量
    # network_mode: "host"
    # 如果需要查看日志,挂载容器中的/opt路径出来即可.
    volumes:
      - /data/apollo/logs:/opt
    ports:
      - "8070:8070"
      - "8080:8080"
      - "8081:8081"
      - "8090:8090"
      - "8091:8091"
    environment:
      # 开启Portal,默认端口: 8070
      PORTAL_DB: jdbc:mysql://192.168.1.249:3306/ApolloPortalDB?characterEncoding=utf8
      PORTAL_DB_USER: root
      PORTAL_DB_PWD: hurongbao123456
      # 开启dev环境, 默认端口: config 8080, admin 8090
      DEV_DB: jdbc:mysql://192.168.1.249:3306/ApolloConfigDBDev?characterEncoding=utf8
      DEV_DB_USER: root
      DEV_DB_PWD: hurongbao123456
      DEV_LB: 192.168.1.240
      DEV_URL: http://192.168.1.240:8080
networks:
  default:
    external:
      name: net-spring-db

**Comment by idoop** [comment]
已经指定了`DEV_DB`,就不要指定`DEV_URL`,`Portal`的[环境参数](https://github.com/idoop/docker-apollo#environment-%E5%8F%82%E6%95%B0)里已经说明了.

**Comment by jackenwjk** [comment]
如果我要指定meta_server怎么指定呢？
![image](https://user-images.githubusercontent.com/9586494/49198362-b8daea80-f3cd-11e8-83c2-6d324263872f.png)

**Comment by idoop** [comment]
MetaServer的地址就是Config服务,假设你想起来dev环境的,那就指定`DEV_DB`,`DEV_DB_USER`,`DEV_DB_PWD`,并把端口暴露出来,可以使用host网络模式,然后你访问ip+port(没指定那就是默认的8080)

**Comment by jackenwjk** [comment]
dev_meta和数据库不在服务器，这样改是不是只有dev_meta和数据库在同一个服务器才启效果呢？我现在的compose是：
version: '2'
services:
  apollo:
    image: idoop/docker-apollo:latest
    # portal若出现504错误,则将网络模式改为host. host模式下如果想改端口,参考下方修改端口的环境变量
    #network_mode: "host"
    # 如果需要查看日志,挂载容器中的/opt路径出来即可.
    volumes:
      - /data/apollo/logs:/opt
    ports:
      - "8070:8070"
      - "8080:8080"
      - "8090:8090"
    environment:
      # 开启Portal,默认端口: 8070
      PORTAL_DB: jdbc:mysql://192.168.1.249:3306/ApolloPortalDB?characterEncoding=utf8
      PORTAL_DB_USER: root
      PORTAL_DB_PWD: hurongbao123456
      #DEV_URL: http://192.168.1.240:8080
      # 开启dev环境, 默认端口: config 8080, admin 8090
      DEV_DB: jdbc:mysql://192.168.1.249:3306/ApolloConfigDBDev?characterEncoding=utf8
      DEV_DB_USER: root
      DEV_DB_PWD: hurongbao123456
      DEV_LB: 192.168.1.240

      # 开启dev环境, 默认端口: config 8080, admin 8090
      #FAT_DB: jdbc:mysql://192.168.1.249:3306/ApolloConfigDBFAT?characterEncoding=utf8
      #FAT_DB_USER: root
      #FAT_DB_PWD: hurongbao123456
      #FAT_LB: 192.168.1.240
networks:
  default:
    external:
      name: net-spring-db
启动之后报：
![image](https://user-images.githubusercontent.com/9586494/49199923-54bc2480-f3d5-11e8-9ce8-b6f47361ea01.png)
![image](https://user-images.githubusercontent.com/9586494/49199933-6f8e9900-f3d5-11e8-89d5-ab0f4ee57956.png)

**Comment by idoop** [comment]
你的docker-compose没问题,应该是数据库配置问题,确认`ApolloPortalDB`库中`ServerConfig`表的`apollo.portal.envs`字段已中填上`dev`,确认`ApolloConfigDBDev`库中`ServerConfig`表的`eureka.service.url`字段为`http://localhost:8080/eureka/`.因为你是在同一个容器中起来portal和dev环境,所以可以填`localhost`.然后可以先用`host`网络模式,方便排除网络问题,没问题了再用NAT网络和指定端口.
``` yaml
version: '2'
services:
  apollo:
    image: idoop/docker-apollo:latest
    network_mode: "host"
    volumes:
      - /data/apollo/logs:/opt
    environment:
      PORTAL_DB: jdbc:mysql://192.168.1.249:3306/ApolloPortalDB?characterEncoding=utf8
      PORTAL_DB_USER: root
      PORTAL_DB_PWD: hurongbao123456
      DEV_DB: jdbc:mysql://192.168.1.249:3306/ApolloConfigDBDev?characterEncoding=utf8
      DEV_DB_USER: root
      DEV_DB_PWD: hurongbao123456
```
